### ISSUE TITLE
Can't update the value of a NUMBER field type

### ISSUE THREAD

**Issue by taikiinoue45** [github/update-project-action#171]
The following YAML file is my  GitHub Action workflow.
※ Please note that for security reasons, some parts have been removed or replaced with dummy values.

```yaml
name: update-project-field
on:
  issues:
    types: [edited]
jobs:
  update-project-field:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get issue node ID
        run: echo "content_id=$(jq -r '.issue.node_id' < $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Update field value
        uses: github/update-project-action@v3
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          organization: my_organization
          project_number: 1
          content_id: ${{ env.content_id }}
          field: my_field
          value: 0
        continue-on-error: true
```

When executing the above workflow, the field is not updated. And this is the part of workflow run logs.

```shell
Run github/update-project-action@v3
  with:
    github_token: ***
    organization: my_organization
    project_number: 1
    content_id: xxxxxxxxxxxxxxxxxx
    field: my_field
    value: 0
    operation: update
  env:
    content_id: xxxxxxxxxxxxxxxxxx
Inputs: {"contentId":"xxxxxxxxxxxxxxxxxx","fieldName":"my_field","projectNumber":1,"owner":"my_organization","value":"0","operation":"update"}
Found content: {"id":"xxxxxxxxxxxxxxxxxx","project":{"number":1,"owner":{"login":"my_field"}},"field":{"value":0}}
Found project: "xxxxxxxxxxxxxxxxxx"
Found Field: {"id":"xxxxxxxxxxxxxxxxxx","name":"my_field","dataType":"NUMBER"}
```

I believe the issue is that, although I'm trying to update the value of the NUMBER field, the `value` in `Inputs:` is being passed as "0" in string format. Actually, the `field.value` in `Found content:` is 0 as a numeric value. As shown in the YAML file, the value is correctly specified as a numeric 0. Furthermore, changing the field type of my_field from NUMBER to TEXT allows the update to succeed. Therefore, I believe there is no issue with my workflow or token permissions.
